#!/bin/bash

# Source tutorial run functions
source $WM_PROJECT_DIR/bin/tools/RunFunctions

# Get application name
application=`getApplication`

# Compile
wmake ..

# Mesh
blockMesh

# Run
runApplication ./test_multicomponentAlloy --log_level=all

#------------------------------------------------------------------------------
