#!/bin/bash

# Source tutorial run functions
source $WM_PROJECT_DIR/bin/tools/RunFunctions

# Get application name
application=`getApplication`

if [ ! -f log.decomposePar ]; then
    ./Allrun.pre
fi

# Run
runParallel $application

# Reconstruct case
runApplication reconstructPar -newTimes -latestTime

python3 convert_vtk.py
python3 generate_pvd.py
python3 plot_line.py
python3 plot_sump.py

#------------------------------------------------------------------------------
