#!/bin/bash

# Source tutorial run functions
source $WM_PROJECT_DIR/bin/tools/RunFunctions

# Get application name
application=`getApplication`

if [ ! -f log.decomposePar ]; then
    ./Allrun.pre
fi

postProcess -func 'grad(T)' -time 0
postProcess -func 'surfaces' -time 0

# Run
runParallel $application

# Reconstruct case
runApplication reconstructPar -newTimes -latestTime

#------------------------------------------------------------------------------
